import Head from "next/head";
import styles from "../styles/Home.module.css";

import TodoForm from "../components/todo-form";
import TodoList from "../components/todo-list";
import { useContext } from "react";
import AuthContext from "../contexts/auth-context";
import Login from "../components/login";

export default function Home() {
  const { authUser, signOut } = useContext(AuthContext);
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJs Practice</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {authUser ? (
          <>
            <button onClick={signOut}>logout</button>
            <h1>Todo app</h1>
            <TodoForm />
            <TodoList />
          </>
        ) : (
          <Login />
        )}
      </main>
    </div>
  );
}
